endereco:
    path:     /
    defaults: { _controller: "ImaginativoTSBundle:Endereco:index" }

endereco_show:
    path:     /{id}/show
    defaults: { _controller: "ImaginativoTSBundle:Endereco:show" }

endereco_new:
    path:     /new
    defaults: { _controller: "ImaginativoTSBundle:Endereco:new" }

endereco_create:
    path:     /create
    defaults: { _controller: "ImaginativoTSBundle:Endereco:create" }
    requirements: { _method: post }

endereco_edit:
    path:     /{id}/edit
    defaults: { _controller: "ImaginativoTSBundle:Endereco:edit" }

endereco_update:
    path:     /{id}/update
    defaults: { _controller: "ImaginativoTSBundle:Endereco:update" }
    requirements: { _method: post|put }

endereco_delete:
    path:     /{id}/delete
    defaults: { _controller: "ImaginativoTSBundle:Endereco:delete" }
    requirements: { _method: post|delete }
