<?php

namespace Proxies\__CG__\Imaginativo\Bundle\TSBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Endereco extends \Imaginativo\Bundle\TSBundle\Entity\Endereco implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Endereco' . "\0" . 'id', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Endereco' . "\0" . 'logradouro', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Endereco' . "\0" . 'bairro', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Endereco' . "\0" . 'cidade', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Endereco' . "\0" . 'uF', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Endereco' . "\0" . 'cEP');
        }

        return array('__isInitialized__', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Endereco' . "\0" . 'id', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Endereco' . "\0" . 'logradouro', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Endereco' . "\0" . 'bairro', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Endereco' . "\0" . 'cidade', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Endereco' . "\0" . 'uF', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Endereco' . "\0" . 'cEP');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Endereco $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogradouro($logradouro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogradouro', array($logradouro));

        return parent::setLogradouro($logradouro);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogradouro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogradouro', array());

        return parent::getLogradouro();
    }

    /**
     * {@inheritDoc}
     */
    public function setBairro($bairro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBairro', array($bairro));

        return parent::setBairro($bairro);
    }

    /**
     * {@inheritDoc}
     */
    public function getBairro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBairro', array());

        return parent::getBairro();
    }

    /**
     * {@inheritDoc}
     */
    public function setCidade($cidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCidade', array($cidade));

        return parent::setCidade($cidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getCidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCidade', array());

        return parent::getCidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setUF($uF)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUF', array($uF));

        return parent::setUF($uF);
    }

    /**
     * {@inheritDoc}
     */
    public function getUF()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUF', array());

        return parent::getUF();
    }

    /**
     * {@inheritDoc}
     */
    public function setCEP($cEP)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCEP', array($cEP));

        return parent::setCEP($cEP);
    }

    /**
     * {@inheritDoc}
     */
    public function getCEP()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCEP', array());

        return parent::getCEP();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
