<?php

namespace Proxies\__CG__\Imaginativo\Bundle\TSBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Equipe extends \Imaginativo\Bundle\TSBundle\Entity\Equipe implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Equipe' . "\0" . 'id', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Equipe' . "\0" . 'nome', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Equipe' . "\0" . 'descricao', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Equipe' . "\0" . 'obs', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Equipe' . "\0" . 'dtCriacao', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Equipe' . "\0" . 'conta', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Equipe' . "\0" . 'membros', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Equipe' . "\0" . 'status', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Equipe' . "\0" . 'responsavel');
        }

        return array('__isInitialized__', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Equipe' . "\0" . 'id', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Equipe' . "\0" . 'nome', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Equipe' . "\0" . 'descricao', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Equipe' . "\0" . 'obs', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Equipe' . "\0" . 'dtCriacao', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Equipe' . "\0" . 'conta', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Equipe' . "\0" . 'membros', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Equipe' . "\0" . 'status', '' . "\0" . 'Imaginativo\\Bundle\\TSBundle\\Entity\\Equipe' . "\0" . 'responsavel');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Equipe $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescricao($descricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescricao', array($descricao));

        return parent::setDescricao($descricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescricao', array());

        return parent::getDescricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setObs($obs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObs', array($obs));

        return parent::setObs($obs);
    }

    /**
     * {@inheritDoc}
     */
    public function getObs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObs', array());

        return parent::getObs();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtCriacao($dtCriacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtCriacao', array($dtCriacao));

        return parent::setDtCriacao($dtCriacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtCriacao', array());

        return parent::getDtCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function addMembro(\Imaginativo\Bundle\TSBundle\Entity\Membro $membros)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMembro', array($membros));

        return parent::addMembro($membros);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMembro(\Imaginativo\Bundle\TSBundle\Entity\Membro $membros)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMembro', array($membros));

        return parent::removeMembro($membros);
    }

    /**
     * {@inheritDoc}
     */
    public function getMembros()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMembros', array());

        return parent::getMembros();
    }

    /**
     * {@inheritDoc}
     */
    public function setConta(\Imaginativo\Bundle\TSBundle\Entity\Conta $conta = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConta', array($conta));

        return parent::setConta($conta);
    }

    /**
     * {@inheritDoc}
     */
    public function getConta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConta', array());

        return parent::getConta();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setResponsavel(\Imaginativo\Bundle\TSBundle\Entity\Membro $responsavel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResponsavel', array($responsavel));

        return parent::setResponsavel($responsavel);
    }

    /**
     * {@inheritDoc}
     */
    public function getResponsavel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponsavel', array());

        return parent::getResponsavel();
    }

}
